package:
  name: intakebuilder
  version: 2.0.1

source:
  #git_url: https://github.com/aradhakrishnanGFDL/CatalogBuilder.git
  path: .

build:
      script: "{{ PYTHON }} -m pip install . -vv"
      number: 0
      noarch: python
      always_include_files:
          - gen_intake_gfdl.py
          - cats/gfdl_template.json
outputs:
    - name: intakebuilder
      files:
        - intakebuilder/*
        - gen_intake_gfdl.py
        - cats/gfdl_template.json
        
requirements:
  host: 
    - python
    - pip 
  run:
    - python
    - click
    - pandas
    - xarray
    - pytest
    - conda-forge::intake-esm=2023.7.7
test:
  imports:
    - intakebuilder 

about:
  home:
